version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  upload-app:
    image: "lquoccuongl/gift4her:v0.0.2"
    container_name: upload-app
    ports:
      - "8080:8080"
    volumes:
      - /upload/:/data/upload
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://upload-db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - upload-db
    networks:
      - mynetwork

  upload-db:
    image: "postgres:13"
    container_name: upload-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /postgres/:/data/postgres
    restart: on-failure
    networks:
      - mynetwork